---
# This playbook helps setup an Object Storage Server via MinIO
- name: MinIO install playbook

  hosts: linux

  tasks: 
    # Creates minio user, with nologin shell, and home directory
    - name: Create minio user
      ansible.builtin.user:
        name: minio
        shell: /sbin/nologin
        home: /opt/minio 

    # Create bin directory and parent directories if needed
    - name: Create bin directory
      ansible.builtin.file:
        path: /opt/minio/bin
        state: directory
        mode: '0755'

    # Download binaries into bin directory created from above
    - name: Download binaries
      ansible.builtin.get_url:
        url: https://dl.minio.io/server/minio/release/linux-amd64/minio
        dest: /opt/minio/bin/minio
        mode: '0440'
        # validate_certs: false   ## should only activate when necessary

    # Grant 'all' executable permissions to bin directory 
    - name: Make bin directory executable
      ansible.builtin.file:
        path: /opt/minio/bin/
        state: touch
        mode: a+x

    # create as a daemon service
    - name: Create daemon service
      ansible.builtin.file:
        path: /etc/systemd/system/minio.service
        state: touch
        mode: '0440'

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start service MinIO, if not started
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

    # Configure Firewalld
    ## REQUIRES: ansible.posix
    ## INSTALLATION: `ansible-galaxy collection install ansible.posix`
    ### See Additional Notes On Documentation, If Required
    - name: Permanently permit traffic in public zone on port 9000/tcp
      ansible.posix.firewalld:
        port: 9000/tcp
        zone: public
        state: enabled
        permanent: true

    # BEGIN: telnet localhost 9000      [checking connectivity]
    - name: Checks and waits for port 9000, 10 seconds delay before check
      ansible.builtin.wait_for:
        # host: localhost     ## Default: "127.0.0.1"
        port: 8000
        delay: 10
        timeout: 120          ## Check for 2 minutes

    #< BEGIN: Check status of MinIO
    # - name: Populate service facts
    #   ansible.builtin.service_facts:

    # - name: Print service facts
    #   ansible.builtin.debug:
    #     var: ansible_facts.service
    #> END: Check status of MinIO
    - name: Check status of MinIO
      ansible.builtin.command: systemctl status minio
        
    # # create as a daemon service
    # - name: Create daemon service
    #   ansible.builtin.blockinfile:
    #     create: true
    #     path: /etc/systemd/system/minio.service
    #     block: |
    #         systemctl daemon-reload
    #         systemctl start minio
    #         systemctl enable minio
    #         firewall-cmd --zone=public --add-port=9000/tcp --permanent
    #         telnet localhost 9000
    #         systemctl status minio

    # Edit minio.conf
    - name: Minio config
      ansible.builtin.blockinfile:
        create: true
        path: /opt/minio/minio.conf
        block: |
          -- entries for minio.conf below
            MINIO_VOLUMES="/minio/data/"
            MINIO_OPTS="--address "
            MINIO_ACCESS_KEY="AK************************X"
            MINIO_SECRET_KEY="SK*********************MpH"

    # Edit minio.service
    - name: Minio service config
      ansible.builtin.blockinfile:
        create: true
        path: /etc/systemd/system/minio.service
        block: |
          --------------------------------------------

          [Unit]
          Description=Minio
          Documentation=https://docs.minio.io
          Wants=network-online.target
          After=network-online.target
          AssertFileIsExecutable=/opt/minio/bin/minio

          [Service]
          WorkingDirectory=/opt/minio
          User=minio
          Group=minio
          PermissionsStartOnly=true
          EnvironmentFile=-/opt/minio/minio.conf
          ExecStartPre=/bin/bash -c "[ -n \"${MINIO_VOLUMES}\" ] || echo \"Variable MINIO_VOLUMES not set in /opt/minio/minio.conf\""
          ExecStart=/opt/minio/bin/minio server $MINIO_OPTS $MINIO_VOLUMES
          StandardOutput=journal
          StandardError=inherit
          # Specifies the maximum file descriptor number that can be opened by this process
          LimitNOFILE=65536
          # Disable timeout logic and wait until process is stopped
          TimeoutStopSec=0
          # SIGTERM signal is used to stop Minio
          KillSignal=SIGTERM
          SendSIGKILL=no
          SuccessExitStatus=0
          [Install]
          WantedBy=multi-user.target

          -------------------------------------------

    # Edit default minio file
    - name: Minio default config
      ansible.builtin.blockinfile:
        create: true
        path: /etc/default/minio
        block: |
          MINIO_OPTS="http://minio-1:9000/data http://minio-2:9000/data http://minio-3:9000/data http://minio-4:9000/data"
          MINIO_ACCESS_KEY="AK**************************BX"
          MINIO_SECRET_KEY="SKFz********************FMpH"

    # Edit hosts file
    - name: Update hosts file
      ansible.builtin.blockinfile:
        create: true
        insertafter: "EOF"
        path: /etc/hosts
        block: |
          10.7.7.182    minio-1
          10.7.7.183    minio-2
          10.7.7.184    minio-3
          10.7.7.185    minio-4
          127.0.0.1     localhost

...